name: test

on:
    push:
      branches:
        - develop

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: setup
      run: |
        cd src\App\mod\vcpkg
        bootstrap-vcpkg.bat
        vcpkg install directxtex
        vcpkg install picojson
        vcpkg install freetype
        vcpkg install imgui[core,dx12-binding,win32-binding]:x64-windows
    - name: build
      run: |
        cmake -S src -B build -G "Visual Studio 17 2022"
        cmake --build build
    - name: test
      run: |
        ctest --test-dir build\App\mod\Math
        ctest --test-dir build\App\mod\Utils
